Feature: Brand 페이지 추가
MessyParty/GlimpsFront pull request #15
Opened 2023-03-24 18:21 UTC by yxxnhx

### 작업 내용
- mock 데이터 생성 후 brand 페이지 생성
- 알파벳 버튼 클릭 시 해당 알파벳으로 이동

### 잔여 작업
- api 완성 시 데이터 연결 설정

2023-03-28 12:42 UTC, syoo970 reviewed
윤하님 수고하셨습니다.
API 함수의 query string 부분을 제외하고는 제 개인적인 리뷰라서 반영하지 않으셔도 무방합니다. :)

2023-03-28 12:42 UTC, syoo970 commented on src/apis/perfume.ts
> +};
이 부분 url을 /perfumes로 수정하는게 좋을 것 같습니다.
그리고 query string의 경우 params를 config에서 추가시켜준다면 굳이 url상으로 붙혀주지 않아도 되서 `params { brandname: name }` 이런식으로 수정 해주시면 될것 같습니다

2023-03-28 12:42 UTC, syoo970 commented on src/components/Brand/Brand.tsx
> +    </div>
이 부분은 div 대신 React Fragment로 대체해도 될 것 같습니다.

2023-03-28 12:42 UTC, syoo970 commented on src/components/Brand/components/AlpabetButton/AlphabetButton.tsx
> +                document.getElementById(data.alphabet) as HTMLDivElement,
react 내에서는 사실 가급적 querySelector나 getElementById 같은 사항은 지양하는 편이기는 합니다. 그대신 함수형 컴포넌트에서는 useRef를 통해서 ref를 많이 사용하는 편입니다

2023-03-28 12:42 UTC, syoo970 commented on src/hooks/queries/useInfiniteScroll.ts
> +  return { data, isSuccess, hasNextPage, fetchNextPage, isFetchingNextPage };
이 부분은 useInfiniteQuery를 바로 return 시켜주면 hook 내부에서 구조 분해 할당을 하지 않고 사용하는 컴포넌트에서 구조 분해 할당을 할 수 있습니다

2023-03-28 12:42 UTC, syoo970 commented on src/pages/brand/[pid].tsx
> +
저도 아직 API 연동을 안해서 이 부분에 대한 자세한 코드는 작성하지 않았는데, 추후 queryClient의 prefetchQuery를 통해서 필요 데이터를 SSR로 미리 가져와 캐싱 해둬서 page나 다른 컴포넌트 내부에서 빠르게 데이터를 가져올 수 있습니다

2023-03-29 12:29 UTC, lyle0101 requested changes

2023-03-29 12:29 UTC, lyle0101 commented on src/components/Brand/components/BrandDetail/BrandDetail.tsx
> +    <div>
이 부분도 div 대신 Fragment 를 사용하면 좋을 것 같습니다!

2023-03-29 12:29 UTC, lyle0101 commented on src/pages/brand/index.tsx
> +    <>
여기 있는 Fragment 는 빼도 될 것 같습니다.

2023-03-29 16:28 UTC, yxxnhx commented on src/apis/perfume.ts
> +};
아하 넵! 제가 그 생각을 못했네요! 한번 수정해보겠습니다~

2023-03-29 16:29 UTC, yxxnhx commented on src/hooks/queries/useInfiniteScroll.ts
> +  return { data, isSuccess, hasNextPage, fetchNextPage, isFetchingNextPage };
넵! 반영하여 변경해보겠습니다!

2023-03-29 16:29 UTC, yxxnhx commented on src/components/Brand/components/AlpabetButton/AlphabetButton.tsx
> +                document.getElementById(data.alphabet) as HTMLDivElement,
안녕하세요! useRef를 이용해서 수정해보려고 하는데 id 값을 넣지 않고는 그냥 하면 계속해서 그냥 쭉 하단으로 스크롤만 되더라구요ㅠㅠ 혹시 제가 참고할만한 자료나 방법이 있을까요? 일단 변경한 상태로 커밋을 남겨두었습니다!

2023-03-30 01:02 UTC, syoo970 commented on src/components/Brand/components/AlpabetButton/AlphabetButton.tsx
> +                document.getElementById(data.alphabet) as HTMLDivElement,
이럴 경우 저라면 `const refs = useRef<Array<HTMLDivElement>>([])`으로 ref list를 만들고 해당 refs를 prop으로 알파벳버튼 컴포넌트에 내려줄것 같습니다.

2023-04-28 11:21 UTC, merged