Feat: 공통 컴포넌트 BrandCard 추가
MessyParty/GlimpsFront pull request #16
Opened 2023-03-24 19:03 UTC by yxxnhx

- 공통으로 사용될 BrandCard 작업하여 스토리북에도 추가하였습니다

2023-03-29 12:33 UTC, lyle0101 requested changes

2023-03-29 12:33 UTC, lyle0101 commented on src/components/BrandCard/BrandCard.tsx
> +  }
사용하지 않는 css 구문은 지워주시면 좋을 것 같습니다 :)

2023-03-29 12:33 UTC, lyle0101 commented on src/components/BrandCard/BrandCard.tsx
> +          <div className="perfumeInfo">
다른 className 과 같이 perfume-info 로 통일시켜 주시면 좋을 것 같습니다!

2023-03-29 16:32 UTC, yxxnhx commented on src/components/BrandCard/BrandCard.tsx
> +  }
앗 지운다는걸 깜빡했네요ㅠㅠ 감사합니다!

2023-03-29 16:32 UTC, yxxnhx commented on src/components/BrandCard/BrandCard.tsx
> +          <div className="perfumeInfo">
넵 감사합니다~!

2023-04-05 11:22 UTC, lyle0101 approved these changes

2023-04-05 11:22 UTC, merged