공통 컴포넌트 작업
MessyParty/GlimpsFront pull request #3
Opened 2023-03-01 09:34 UTC by syoo970

### 작업 내용
- 재사용성 있는 input 컴포넌트들 개발
  - input, like 버튼, rating 컴포넌트
- 기타 공통 컴포넌트 개발
  - 모달, 리뷰카드 개발
- 유틸 hook 개발
  - 디바운스 훅 개발
- svg 설정 및 custom svg 컴포넌트 개발

### 추후 보완해야할 점
- like 버튼 api intergration 작업
- input 컴포넌트 custom css 적용 작업

### 논의할 내용
- 기존 rating 컴포넌트의 half는 수평으로 구분 됨, 따라서 rating의 반절(0.5)의 방향에 대한 논의 필요

2023-03-04 05:58 UTC, yxxnhx reviewed
승범님 개발하시느라 수고 많으셨습니다!
제가 아직 많이 부족해서 승범님 코드를 보면서 오히려 공부가 되었네요 코드를 뜯어보면서 개선할 점보다는 의문점이 있어서 하나 질문 남깁니다 별로 중요하진 않아요🥺 코드 정리도 깔끔하게 되어있고 많은 고민을 하시면서 작성하신게 보여서 많은 도움이 되었습니다! 수고하셨습니다👍👍👍

2023-03-04 05:58 UTC, yxxnhx commented on src/components/LikeButton/LikeButton.tsx
> +  initialState?: boolean;
혹시 여기에서는 왜 옵셔널을 쓴건지 알 수 있을까요?
제가 생각하기에는 초기값은 필수값이라고 생각하는데 옵셔널은 있어도 되고 없어도 되는 부분이어서 이 부분이 궁금합니다

2023-03-04 06:33 UTC, syoo970 commented on src/components/LikeButton/LikeButton.tsx
> +  initialState?: boolean;
아 이 부분은 첫째로 likbutton의 데이터가 비동기 데이터이고 또 추후 react-query를 활용할 예정이라서 undefined일 수 있어서 옵셔널을 사용하였구요, 아래 ?? (nullish 연산자)를 사용해서 undefined 일시 false 처리를 해주어서 초기 값이 존재 할때만 해당 props를 명시적으로 넘겨 주기 위해서 그렇게 작성하였습니다

2023-03-04 06:36 UTC, yxxnhx commented on src/components/LikeButton/LikeButton.tsx
> +  initialState?: boolean;
아 그렇군요! 덕분에 하나 더 알아갑니다!👍

2023-03-05 15:05 UTC, lyle0101 requested changes
파일 수가 거의 저의 세배시군요.. 개발하시느라 수고 많으셨습니다!!
리뷰를 늦게 달아 죄송하다는 말씀 먼저 드립니다ㅜㅜ 저도 많이 부족해서 메이저한 리뷰를 달진 못했지만 사소한 거라도 남겨봤습니다 😅 코드 보는 것으로도 많은 도움 되었습니다! 감사합니다 🙇‍♀️

2023-03-05 15:05 UTC, lyle0101 commented on .storybook/main.js
> +    console.log(config.module.rules);
삭제가 필요한 라인 같습니다!

2023-03-05 15:05 UTC, lyle0101 commented on src/components/CustomIcon/PerfumeFull/PerfumeFull.tsx
> +import PerfumeFullIcon from "@root/public/perfum-full-icon.svg";
어어어엄청 마이너하지만 향수 관련 svg 파일 이름들이 perfum 으로 되어 있어서 perfume 으로 수정해도 괜찮을 것 같습니다!

2023-03-05 15:05 UTC, lyle0101 commented on src/components/CustomIcon/QuoteLeft/QuoteLeft.tsx
> +import QutoeLeftIcon from "@root/public/quote-left.svg";
이것도 perfum 과 마찬가지로 QuoteLeftIcon 으로 수정되면 좋을 것 같습니다!

2023-03-05 15:05 UTC, lyle0101 commented on src/components/ReviewCard/ReviewCard.tsx
> +}
ReviewCardProps 에서 없으면 안되는 값도 있을텐데 혹시 전부 옵셔널인 이유가 있을까요?

2023-03-05 15:05 UTC, lyle0101 commented on src/components/ReviewCard/ReviewCard.tsx
> +`;
이번에는 style 관련 파일은 분리하지 않는 방향으로 가는걸까요?

2023-03-06 00:27 UTC, syoo970 commented on .storybook/main.js
> +    console.log(config.module.rules);
앗... 미쳐 신경쓰지 못했습니다.. 반영하도록 하겠습니다

2023-03-06 00:30 UTC, syoo970 commented on src/components/ReviewCard/ReviewCard.tsx
> +}
사실 이 부분은 지수님 의견처럼 title이나 author 같은 사항은 옵셔널이 아닌게 좀 더 명확하긴 합니다...
이렇게 짠 이유는 개발시 좀 더 편하게 하려는 의도가 있었는데 수정하는게 좋을 것 같습니다 감사합니다 🙏

2023-03-06 00:32 UTC, syoo970 commented on src/components/ReviewCard/ReviewCard.tsx
> +`;
넵 맞습니다.
예전에는 분리하는 방향으로 가는게 더 코드 가독성면에서 더 좋을 거라 생각했는데, 요즘 다시 생각 드는게 사실 styled 컴포넌트와 관련된 코드가 많지 않으니 같은 파일 스코프로 묶어두는게 style 관련 css 코드를 보는데 더 좋은 것 같아서 요즘에는 다시 묶어서 하고 있습니다

2023-03-06 12:24 UTC, merged